#! /bin/sh

CURRENT=$(cd $(dirname $0);pwd)

JAVACMD=java
if [ -f $CURRENT/java ]; then
    JAVACMD=$CURRENT/java
fi

exec $JAVACMD --module-path $CURRENT/../libs -m jp.cafebabe.plmaker/jp.cafebabe.plmaker.cli.Main "$@"
