name: build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - name: Git Tag name
        id: vars
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF##**/v}" >> $GITHUB_OUTPUT

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build project
        run: |
          ./gradlew build

  codecov:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.vars.outputs.branch }}
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Jacoco Report
        run:
          ./gradlew jacocoTestReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
