name: build

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      
      - name: Build project with dagger.io
        run:
          go run ci/build/main.go
