name: create_pull_request

on:
  push:
    branches:
      - releases/v*

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create pull request
        run: |
          ./.bin/create-pull-request.sh 
